broadinstitute/cromwell-tools

- pull_request_template.md
- requirements.txt
- setup.py
> Freeze libraries in requirements.txt. (639)

- setup.py
I introduced a dumb TYPO/BUG in my previous, this PR is to fix it.
> Fix a typo/bug in setup.py.

- cromwell_tools/cromwell_tools.py
- cromwell_tools/scripts/cromwell-tools
- cromwell_tools/tests/test_cromwell_tools.py
Consolidating dead branches to improve short-term usability while I wait for refactor.
> Allow URL in secrets file

- cromwell_tools/cromwell_tools.py
- cromwell_tools/scripts/cromwell-tools
- cromwell_tools/tests/test_cromwell_tools.py
> Add on_hold param to start_workflow

- cromwell_tools/cromwell_tools.py
- cromwell_tools/tests/test_cromwell_tools.py
Implement query workflows and release workflow functions.
> Implement release and query workflows functions.

- README.rst
- cromwell_tools/cli.py
- cromwell_tools/tests/test_cromwell_api.py
> Fix CLI arguments.

- notebooks/monitoring.sh
> fixed df bug for getting total disk space

- notebooks/plot_benchmark.py
> plots max usage from shards & removes 'attempts' from task call name

- cromwell_tools/cli.py
> Fix for #46.

- cromwell_tools/cli.py
- cromwell_tools/cromwell_api.py
- cromwell_tools/cromwell_auth.py
- cromwell_tools/tests/test_cromwell_api.py
- cromwell_tools/tests/test_cromwell_auth.py
- notebooks/Quickstart/Examples/hello_world.wdl
- notebooks/Quickstart/Examples/helloworld.wdl
- notebooks/Quickstart/Examples/inputs.json
- notebooks/Quickstart/quickstart.ipynb
This PR adds a quickstart example jupyter notebook for the new cromwell-tools API interface.
> Add quickstart examples

- cromwell_tools/cli.py
> Change expected name for service-account-key.

- cromwell_tools/cli.py
- cromwell_tools/cromwell_api.py
- cromwell_tools/cromwell_auth.py
- cromwell_tools/tests/test_cromwell_api.py
- cromwell_tools/tests/test_cromwell_auth.py
- notebooks/Quickstart/quickstart.ipynb
Note: This PR fixes a set of small bugs in the code base but uses a workaround around the CLI. In order to add unit tests for the CLI and make it easier to iterate later, the CLI needs to be refactored.
---
> Fix bugs with CLI and improve the CLI stdout.

- cromwell_tools/cromwell_auth.py
- https://app.zenhub.com/workspaces/dcp-backlogs-5ac7bcf9465cb172b77760d9/issues/humancellatlas/secondary-analysis/431
---
- Add a token checker before making the header to avoid token expiration by refreshing the token if it's required with OAuth.
---
_Please provide instructions about how should a reviewer test/verify the changes in this PR:_
- The unit tests should pass, which implies that the property changes are not affecting the Auth API.
---
_Please ensure the following when opening a PR:_
---
_Please append follow-up discussions and issues during the review process below:_
- No follow-up discussions.
> Add token checker before making the header to avoid token expiration.

- Dockerfile
- cromwell_tools/cli.py
- cromwell_tools/cromwell_api.py
- cromwell_tools/tests/test_cromwell_api.py
- cromwell_tools/utilities.py
- requirements.txt
- setup.py
- https://github.com/HumanCellAtlas/secondary-analysis/issues/503
---
- This PR fixes the CLI parameters, especially focused on the `/submit` command. 
- Oracle's Java 8 installer seems to be broken now when downloading from the docker build context, switching to OpenJDK for future convenience!
- For clarity, take out the `tenacity` retry policy from the library, so the `/submit` command run and fail much faster, and the user-friendly message is shipped to users directly without being shadowed.
---
_Please provide instructions about how should a reviewer test/verify the changes in this PR:_
To test the cromwell-tools: …
> Fix the issues with CLI

- cromwell_tools/tests/test_utilities.py
- cromwell_tools/utilities.py
- https://github.com/HumanCellAtlas/secondary-analysis/issues/541
---
- Fix the bug with the conditions.
---
_Please provide instructions about how should a reviewer test/to verify the changes in this PR:_
- Please review the update conditional logic.
---
_Please ensure the following when opening a PR:_
---
_Please append follow-up discussions and issues during the review process below:_
- No follow-up discussions.
> Fix a bug that prevents submitting a zipped file as dependency.

- cromwell_tools/cromwell_auth.py
- cromwell_tools/tests/test_cromwell_auth.py
- No issue is linked to this PR.
---
- Add support for service account contents.
---
_Please provide instructions about how should a reviewer test/verify the changes in this PR:_
---
_Please ensure the following when opening a PR:_
---
_Please append follow-up discussions and issues during the review process below:_
- No follow-up discussions.
> Add support for service account contents.

- cromwell_tools/__init__.py
- cromwell_tools/cli.py
- cromwell_tools/cromwell_api.py
- cromwell_tools/cromwell_auth.py
- cromwell_tools/tests/test_cromwell_api.py
- cromwell_tools/tests/test_cromwell_auth.py
- cromwell_tools/tests/test_utilities.py
- cromwell_tools/utilities.py
- docs/conf.py
- notebooks/benchmark.py
- notebooks/format_benchmark.py
- notebooks/plot_benchmark.py
- setup.py
- https://broadinstitute.atlassian.net/jira/software/projects/GH/boards/530?selectedIssue=GH-128
---
- Format the code base with Black.
---
_Please provide instructions about how should a reviewer test/verify the changes in this PR:_
- Please check if the 2 tests (linting + unit) are both passing.
- Please check if there are any deal-breakers that Black provides here, for instance:
- Do you think it's OK to always add `()` everywhere? Black adds them almost everywhere.
- Do you think it's OK to have extra lines?
- Do you think it's OK to always dedent the closing brackets and add a trailing comma? Black does that to …
> Format with Black and Flake8

- cromwell_tools/cli.py
- cromwell_tools/cromwell_api.py
- cromwell_tools/tests/test_cromwell_api.py
- No issue is linked to this PR.
- No changes.
> Roughly implement the /metadata in both API and CLI.

- setup.py
> Fix a typo in the setup.py file.

- cromwell_tools/cromwell_api.py
- cromwell_tools/cromwell_auth.py
- cromwell_tools/exceptions.py
- cromwell_tools/utilities.py
- Use type annotations so it's much easier for IDEs and static tools to analyze and infer the code.
- Make the docstrings cleaner.
- Create placeholder directories for the next PR to better organize the code without breaking the existing downstream consumers. This also helps with adding upcoming sub-packages to the tool.
- Replace typing hints in the docstrings with recommended type annotations from the `typing` module. There should be **NO** functional changes.
- Extract exceptions into a standalone module. There should be **NO** functional changes.
- Create some placeholder directories.
- THANKS FOR YOUR TIME :)
> Stronger types and more hierarchical directory structures for upcoming sub-packages

- .travis.yml
- https://github.com/broadinstitute/cromwell-tools/issues/87
- I followed the instructions on Travis: https://docs.travis-ci.com/user/deployment/pypi/
> Automate the PyPI release process with Travis CI.

- README.rst
- Fixes #90 
- Fixes the broken links in readme file.
> Fix the broken links on readme.

- cromwell_tools/cromwell_api.py
- cromwell_tools/tests/test_cromwell_api.py
Add functionality to patch a workflow's labels to cromwell_api
- No changes.
> Add patch labels to api

- cromwell_tools/cli.py
- cromwell_tools/diag/task_runtime.py
- No issue is linked to this PR.
- No changes.
> Add task runtime diagnostic

- requirements.txt
Missed adding requirements in original PR
- No changes.
> Update requirements for task_runtime functionality

- cromwell_tools/__init__.py
- cromwell_tools/cli.py
- cromwell_tools/tests/test_cli.py
- setup.py
- https://github.com/broadinstitute/cromwell-tools/issues/29
- Add test cases for CLI.
> Add test cases for CLI.

- cromwell_tools/cli.py
- cromwell_tools/cromwell_api.py
- cromwell_tools/utilities.py
This pull request adds support for python versions prior to python3.6 (namely adding support for python3.5). This is in reference to issue #104 
- Removal of f-string literals, replacing with C-style string formatting instead
> ADD #104 remove use of f-string literals to allow support for python3.5

- .github/workflows/pr-tests.yml
- .pre-commit-config.yaml
- README.rst
- codecov.yml
- cromwell_tools/tests/test_utilities.py
- cromwell_tools/utilities.py
- requirements-test.txt
> Update docs and tests to indicate Python3.5 support.
